server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/learn_springboot"
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true